image: docker-all.devops.etat-ge.ch/ch/ge/cti/maven:3-jdk-8

variables:
  # fix for old git version
  GIT_STRATEGY: clone
  GIT_SSL_NO_VERIFY: "true"
  # config Maven
  MAVEN_CLI_OPTS: "--batch-mode"
  
build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile