image: maven:3-jdk-8

variables:
  # fix for old git version
  GIT_STRATEGY: clone
  GIT_SSL_NO_VERIFY: "true"
  # config Maven
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache: 
  paths:
   - .m2/repository/
   - target/
  
build:
  script:
    - mvn $MAVEN_CLI_OPTS compile
    
deploy: 
  script: 
   - mvn $MAVEN_CLI_OPTS deploy -Dmaven.test.skip=true 
  only: 
   - master
    