image: docker-all.devops.etat-ge.ch/maven:3-jdk-8

variables:
  # fix for old git version
  GIT_STRATEGY: clone
  GIT_SSL_NO_VERIFY: "true"
  # config Maven
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  # config SonarQube
  SONAR_MAVEN_GOAL: org.sonarsource.scanner.maven:sonar-maven-plugin:3.4.0.905:sonar
  SONAR_USER_HOME: /builds/sonar
  # config CLM
  CLM_MAVEN_GOAL: com.sonatype.clm:clm-maven-plugin:2.12.1:evaluate
  CLM_SERVER_ID: clm_server
  CLM_APPLICATION_ID: REFERENTIELS-OFS

cache:
  paths:
    - ./.m2/repository
  # keep cache across branch
  key: "$CI_COMMIT_REF_SLUG"
  
stages:
  - build
  - sonarqube
  - clm
  - deploy
  - release

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS package $SONAR_MAVEN_GOAL -Dsonar.host.url=$SonarQube_URL -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$(git log --pretty=format:%H origin/master..$CI_COMMIT_SHA | tr '\n' ',') -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.unique_issue_per_inline=true -Dsonar.gitlab.max_blocker_issues_gate=-1 -Dsonar.gitlab.max_critical_issues_gate=-1
  except : 
    - master
    
sonarqube: 
  stage: sonarqube
  script: 
   - mvn $MAVEN_CLI_OPTS install $SONAR_MAVEN_GOAL -Dsonar.host.url=$SonarQube_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.max_blocker_issues_gate=-1 -Dsonar.gitlab.max_critical_issues_gate=-1 
  only: 
   - master

clm: 
  stage: clm
  script: 
   - mvn $MAVEN_CLI_OPTS $CLM_MAVEN_GOAL -Dclm.applicationId=$CLM_APPLICATION_ID -Dclm.serverUrl=$CLM_URL -Dclm.serverId=$CLM_SERVER_ID
  only: 
   - master

deploy: 
  stage: deploy
  script: 
   - mvn $MAVEN_CLI_OPTS deploy -Dmaven.test.skip=true
  only: 
   - master
   
release:
  stage: release
  script: 
   - git config --global user.email "***REMOVED***"
   - git config --global user.name "***REMOVED***"
   - git checkout $CI_COMMIT_REF_NAME
   - mvn $MAVEN_CLI_OPTS release:prepare release:perform -Dresume=false -Darguments="-DskipTests" -DskipTests -Dusername=$SCM_USER -Dpassword=$SCM_PASSWORD -DautoVersionSubmodules=true -U
  when: manual
  only:
    - master  